name: Java CI with Gradle

on:
  push:
    branches-ignore: []
  pull_request:
    branches-ignore: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew test jacocoTestReport

    - name: Upload JaCoCo Test Report
      uses: actions/upload-artifact@v2
      with:
          name: jacoco_reports
          path: build/reports/jacoco/test/html

      with:
          name: jacoco_reports
          path: build/reports/jacoco/test/html
